version: '3'

services:
  www:
    build: './src/www'
    volumes:
      - './src/www/html:/usr/share/nginx/html'
    ports:
      - '8080:80'
  nodejs:
    build: 
      context: './src/www'
      dockerfile: Dockerfile.nodejs
    volumes:
      - './src/www/html:/usr/share/nginx/html'
    ports:
      - '8080:80'
